version: '3'

services:
    redis:
        image: redis
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
            resources:
                # 限制每个最多1cpu
                limits:
                    cpus: 1
                    memory: 2G
        command: redis-server /etc/redis/redis.conf
        volumes:
          - type: bind
            read_only: true
            source: ${REDIS_CONF}
            target: /etc/redis/redis.conf
        networks: # 指定网络名, 使redis和webpos都在同一个网络命名空间下
            - webpos

networks:
    webpos:
