version: '3'

services:
    redis:
        image: redis
        network_mode: host
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
            resources:
                # 限制每个最多1cpu
                limits:
                    cpus: 1
                    memory: 2G
        volumes:
          - type: bind
            read_only: true
            source: ${REDIS_CONF}
            target: /etc/redis/redis.conf
